defaults:
  - _self_
  - model: mobilenetv3
  - optimizer: adam
  - dataset: data

experiment_name: "finetune_mobilenetv3"
num_epochs: 2
batch_size: 32
learning_rate: 1e-3
train_split: 0.8
val_split: 0.1
test_split: 0.1
seed: 42
precision: 32
monitor: "val_loss"
patience: 5
mode: "min"

wandb:
  project: "plant_disease_detection"
  run_name: "finetune_mobilenetv3"